// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADV4vpP6W1kUkp94gkbzgHeo8d_CyH6bE',
    appId: '1:60230208422:web:cb46d6a9f96e9642e5dd67',
    messagingSenderId: '60230208422',
    projectId: 'bump-to-birth-d550f',
    authDomain: 'bump-to-birth-d550f.firebaseapp.com',
    storageBucket: 'bump-to-birth-d550f.appspot.com',
    measurementId: 'G-364T1F4W9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq4TQVMoSp_jsiHN9vh_EhifQjO5bF9cQ',
    appId: '1:60230208422:android:8b17e6be2f4f4d63e5dd67',
    messagingSenderId: '60230208422',
    projectId: 'bump-to-birth-d550f',
    storageBucket: 'bump-to-birth-d550f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwT-cldYV6_jUjkh-7agGEFRjf1jFxClQ',
    appId: '1:60230208422:ios:ee5d11fed3df5883e5dd67',
    messagingSenderId: '60230208422',
    projectId: 'bump-to-birth-d550f',
    storageBucket: 'bump-to-birth-d550f.appspot.com',
    iosBundleId: 'com.example.bumpToBirth',
  );
}
